name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: 'latest'

    - name: Build Flutter Web App
      run: |
        cd src  # Navigate to the src directory
        flutter pub get
        flutter build web --release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./src/build/web
